// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr-F5NX8Is9saeFkUZhJB1NkCref_2GJI',
    appId: '1:19009988284:web:e41a66664495e68c79d2b9',
    messagingSenderId: '19009988284',
    projectId: 'flash-chat-e3dea',
    authDomain: 'flash-chat-e3dea.firebaseapp.com',
    storageBucket: 'flash-chat-e3dea.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJKLhGfpNmOXriTnunAp3J5BdkIC8Oyfw',
    appId: '1:19009988284:android:6d198a1dac6cabd379d2b9',
    messagingSenderId: '19009988284',
    projectId: 'flash-chat-e3dea',
    storageBucket: 'flash-chat-e3dea.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAr-F5NX8Is9saeFkUZhJB1NkCref_2GJI',
    appId: '1:19009988284:web:637894cd3fa692d379d2b9',
    messagingSenderId: '19009988284',
    projectId: 'flash-chat-e3dea',
    authDomain: 'flash-chat-e3dea.firebaseapp.com',
    storageBucket: 'flash-chat-e3dea.appspot.com',
  );
}